[package]
name = "dockerfile_builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dockerfile_derive = {path = "../dockerfile_derive"}
eyre = "0.6.8"

[dev-dependencies]
expect-test = "1.4.1"
