[package]
name = "dockerfile_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
eyre = "0.6.8"
proc-macro2 = "1.0.63"
quote = "1.0.28"
syn = { version = "2.0.18", features = ["extra-traits", "printing"] }
